### PR TITLE
feat: Update shaka to v3.3.2 + UI

### PR DESCRIPTION
**Pull request by joeyparrish**
Also removes some unnecessary cruft (debug version, externs) and loads
all scripts and CSS from a Google CDN.

### CODE REVIEW

**Comment by joeyparrish** [comment]
Ping!

**Comment by joeyparrish** [comment]
Ping!

**Comment by joeyparrish** [comment]
Ping!

**Review by philcluff — APPROVED** [review]
Sorry for the delay!

**Pull request merged**
